

Numpy Tutorial campusx-- Fundamental package


numpy provides:

An array object of arbitrary homogeneous items
Fast mathematical operations over arrays
Linear Algebra, Fourier Transforms, Random Number Generation
How to use the documentation
Documentation is available in two forms: docstrings provided with the code, and a loose standing reference guide, available from
the NumPy homepage <https://numpy.org>_.

We recommend exploring the docstrings using
IPython <https://ipython.org>_, an advanced Python shell with TAB-completion and introspection capabilities. See below for further instructions.

The docstring examples assume that numpy has been imported as np:

  >>> import numpy as np
Code snippets are indicated by three greater-than signs:

  >>> x = 42
  >>> x = x + 1
Use the built-in help function to view a function's docstring:

  >>> help(np.sort)
  ... # doctest: +SKIP
For some objects, np.info(obj) may provide additional help. This is
particularly true if you see the line "Help on ufunc object:" at the top of the help() page. Ufuncs are implemented in C, not Python, for speed. The native Python help() does not know how to view their help, but our np.info() function does.

To search for documents containing a keyword, do:

  >>> np.lookfor('keyword')
  ... # doctest: +SKIP
General-purpose documents like a glossary and help on the basic concepts of numpy are available under the doc sub-module:

  >>> from numpy import doc
  >>> help(doc)
  ... # doctest: +SKIP
Available subpackages
lib
    Basic functions used by several sub-packages.
random
    Core Random Tools
linalg
    Core Linear Algebra Tools
fft
    Core FFT routines
polynomial
    Polynomial tools
testing
    NumPy testing tools
distutils
    Enhancements to distutils with support for Fortran compilers support and more (for Python <= 3.11).

Utilities
test
    Run numpy unittests
show_config
    Show numpy build configuration
matlib
    Make everything matrices.
__version__
    NumPy version string

Viewing documentation using IPython
Start IPython and import numpy usually under the alias np: import numpy as np. Then, directly past or use the %cpaste magic to paste examples into the shell. To see which functions are available in numpy, type np.<TAB> (where <TAB> refers to the TAB key), or use np.*cos*?<ENTER> (where <ENTER> refers to the ENTER key) to narrow down the list. To view the docstring for a function, use np.cos?<ENTER> (to view the docstring) and np.cos??<ENTER> (to view the source code).

Copies vs. in-place operation
Most of the functions in numpy return a copy of the array argument (e.g., np.sort). In-place versions of these functions are often available as array methods, i.e. x = np.array([1,2,3]); x.sort(). Exceptions to this rule are documented.


Craeting arrays with Numpy array

In [10]:
#np array
import numpy as np

In [13]:
#1D array - You can call it 'Vector'
a = np.array([1,2,3])

In [14]:
type(a)

numpy.ndarray

In [15]:
#2d - You can call it "matrix"
b = np.array([[1,2,3],[4,5,6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(b)

numpy.ndarray

In [23]:
#3d array- You can call it 'Tensor'
c = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])

In [24]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
#dtype
float_arr = np.array([1,2,3], dtype=float)

In [27]:
float_arr

array([1., 2., 3.])

In [32]:
bool_arr = np.array([1,0,3] , dtype=bool)

In [33]:
# a NON ZERO VALUE in python is considered to be true
bool_arr

array([ True, False,  True])

In [34]:
c_arr = np.array([1,2,3,4], dtype=complex)

In [35]:
c_arr

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [36]:
#np.arange - works as range() in python list
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [39]:
#reshape() - get a 2d aray with 5 rows and 2 columns
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [41]:
arr = np.arange(1,13).reshape(3,4)

In [42]:
#shape exceeded
arr.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [43]:
#np.ones() and np.zeros- takes a tupe as input and creates an array with all items as one or zero
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.ones((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
#random number array initialization - generates raandom number in raange of 0 to 1
np.random.random((3,4))

array([[0.99701615, 0.65993638, 0.71537036, 0.70699648],
       [0.98765787, 0.34969189, 0.51837666, 0.68841651],
       [0.72115024, 0.71347096, 0.06433694, 0.25487883]])

In [51]:
#np.linspace() - linear space :- You provide range and numbers- lower range, upper range , number of items to generate
np.linspace(-10,10,10)
#all items are on equal space.

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [53]:
#np.identity() - crates an itentity matrix
np.identity(3 , dtype=int) #default value of dtype is float

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Array Attributes


In [72]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [73]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [75]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
#ndim - stands for "number of dimension"- gives dimension of an array
a1.ndim

1

In [77]:
a2.ndim

2

In [78]:
a3.ndim

3

In [79]:
#shape- gives number of rows and cols
a1.shape
#1d array and 10 items are present

(10,)

In [80]:
a2.shape

(3, 4)

In [81]:
#number of 2d arr present, number of rows, number of cols
a3.shape

(2, 2, 2)

In [82]:
#size - number of items
a3.size

8

In [83]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [84]:
#itemsize - tells the memory occupied by each itmem
a1.itemsize

4

In [85]:
a3.itemsize

4

In [86]:
a2.itemsize

8

In [87]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


Changing DataType

In [90]:
# asdtype

a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

In [96]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)


Array Operations

In [100]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)



array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [103]:
# scalar operations - ek numpy arr pr ek single operator se operate krte ho - one array operations hote hain



# arithmetic operations
a4 ** 4

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]], dtype=int32)

In [107]:
#relational operator- koi number 5 se bada h to true - yha sbhi relational operaator work krte hain
a4 > 5



array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [106]:
a4 == 5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [108]:
#Vector operations on array - operations on two arrays
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [110]:
# arithmetic vector operaations - items should be same
a4 + a5


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [111]:
a4 - a5

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [112]:
a4 / a5

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

Array Functions

In [116]:
a1 = np.random.random((3,3))
a2 = np.round(a1 * 100)

In [117]:
a1

array([[0.54041039, 0.20999239, 0.55496854],
       [0.39940067, 0.16838984, 0.73826024],
       [0.45254221, 0.86611929, 0.15930706]])

In [118]:
a2

array([[54., 21., 55.],
       [40., 17., 74.],
       [45., 87., 16.]])

In [121]:
# max/min/sum- gives sum of all numbers/prod
print(np.max(a1))
print(np.min(a1))
print(sum(a2))


0.866119290206079
0.1593070642302059
[139. 125. 145.]


In [122]:
np.prod(a1)

0.00019525474392822703

In [125]:
# finding minimum in each row -axis = 0 represent row, and axis = 1 represent cols
np.max(a1, axis = 1)

array([0.55496854, 0.73826024, 0.86611929])

In [127]:
#it worksa on max min sum etc functions defined above
np.min(a1, axis =0)

array([0.39940067, 0.16838984, 0.15930706])

In [128]:
np.prod(a1, axis =1)

array([0.06297898, 0.0496517 , 0.06244129])

In [129]:
# mean/median/std/var
np.mean(a1)

0.4543767363279259

In [130]:
np.median(a1, axis = 1)

array([0.54041039, 0.39940067, 0.45254221])

In [131]:
np.var(a1, axis=1)

array([0.02537739, 0.05477156, 0.08406849])

In [132]:
# trignometric Functions
np.sin(a1)

array([[0.51448794, 0.20845245, 0.52691657],
       [0.38886625, 0.16759518, 0.67300213],
       [0.43725325, 0.7618208 , 0.15863408]])

In [133]:
# dot product - just like product of matrix

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [134]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

In [135]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [136]:
#log and exponents
np.log(a1)

array([[-0.61542645, -1.56068401, -0.58884384],
       [-0.91779019, -1.7814735 , -0.30345889],
       [-0.79287425, -0.14373263, -1.83692172]])

In [137]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [142]:
#round/floor/ceil
np.round(np.random.random((2,3)) * 100)

array([[21., 49., 29.],
       [33., 87., 49.]])

In [143]:
np.floor(np.random.random((2,3)) * 100)

array([[69., 74.,  1.],
       [69., 38., 89.]])

In [146]:
np.ceil(np.random.random((2,3)) * 100)

array([[48., 81., 52.],
       [54.,  2., 87.]])

Indexing and Slicing

In [149]:
a1 = np.arange(10)
a2  = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [150]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [153]:
# Indexing - works same as python imdexing
a1[-1]

9

In [154]:
# row , cols
a2[1,2]

6

In [155]:
a2[2,3]

11

In [156]:
a2[1,0]

4

In [157]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [159]:
#number of 2d matrix,row,cols
a3[1,0,1]

5

In [160]:
a3[0,1,0]

2

In [161]:
a3[0,0,0]

0

In [162]:
a3[1,1,0]

6

Slicing

In [163]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
a1[2:5]

array([2, 3, 4])

In [166]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [167]:
#row, all for colon
a2[0,:]

array([0, 1, 2, 3])

In [168]:
a2[:,2]

array([ 2,  6, 10])

In [169]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [170]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [171]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [174]:
a2[1,::3]

array([4, 7])

In [176]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [177]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [179]:
a3 = np.arange(27).reshape(3,3,3)

In [180]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [182]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [183]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [184]:
a3[0,1,:]

array([3, 4, 5])

In [185]:
a3[1, :,1]

array([10, 13, 16])

In [187]:
a3[2, 1:,1:]

array([[22, 23],
       [25, 26]])

In [188]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [191]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

    Iteration of array

In [192]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [195]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [196]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [198]:
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


    Reshaping

In [199]:
#reshape/transpose/revel
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [200]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [201]:
#another way of transpose
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [205]:
 #ravel -converts any n-dimensional arr into 1d arr- forms a new array does not change the original arr
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [206]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

    Stacking - two ways horizontal and vertical

In [ ]:
#horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)


In [207]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [208]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [210]:
#horizontal stacking - hstack((arr1 , arr2))
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [211]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [213]:
#vertical stack - vstack((arr1, arr2)) - webscaping and database ke  data ko ek sath jodno ke kaam aata hai --shape of both arr should be same
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

    splitting - opposite of stacking

In [214]:
#horizontal split
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [215]:
#equal division hona chahiye
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [216]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [218]:
#divides all 3 rows into single arr
np.vsplit(a5 , 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]