    np.sort - returns a copy of  array

In [2]:
import numpy as np

a = np.random.randint(1,100,15)
a


array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [3]:
np.sort(a)

array([10, 19, 24, 34, 35, 41, 41, 46, 50, 64, 70, 75, 82, 88, 96])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[35, 24, 55, 72],
       [37, 11, 56, 70],
       [40, 18, 75, 85],
       [79, 92, 18,  2],
       [79, 19, 37, 64],
       [68,  5, 91, 52]])

In [5]:
np.sort(b)

array([[24, 35, 55, 72],
       [11, 37, 56, 70],
       [18, 40, 75, 85],
       [ 2, 18, 79, 92],
       [19, 37, 64, 79],
       [ 5, 52, 68, 91]])

In [6]:
#axis = 0 -> column-wise sorting
np.sort(b, axis =0)

array([[35,  5, 18,  2],
       [37, 11, 37, 52],
       [40, 18, 55, 64],
       [68, 19, 56, 70],
       [79, 24, 75, 72],
       [79, 92, 91, 85]])

In [7]:
# descending sort
np.sort(a)[::-1]

array([96, 88, 82, 75, 70, 64, 50, 46, 41, 41, 35, 34, 24, 19, 10])

    np.append()-same as python append

In [8]:
np.append(a, 200)

array([ 70,  41,  46,  88,  10,  24,  34,  50,  96,  82,  41,  35,  19,
        75,  64, 200])

In [9]:
b 

array([[35, 24, 55, 72],
       [37, 11, 56, 70],
       [40, 18, 75, 85],
       [79, 92, 18,  2],
       [79, 19, 37, 64],
       [68,  5, 91, 52]])

In [10]:
np.append(b,np.ones((b.shape[0],1)), axis=1)

array([[35., 24., 55., 72.,  1.],
       [37., 11., 56., 70.,  1.],
       [40., 18., 75., 85.,  1.],
       [79., 92., 18.,  2.,  1.],
       [79., 19., 37., 64.,  1.],
       [68.,  5., 91., 52.,  1.]])

    np.concatenate() - concatenates a sequence of arrs along an exiting axis

In [11]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [12]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d) , axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d) , axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

    np.unique() - with the help of unique(), we can get the unique value from an arr given as a parameter in np.unique() method.

In [16]:
e = np.array([1,1,1,1,1,1,2,2,2,3,3,3,3,4,4,5,5,6,6,6,6])

In [17]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

    np.expand_dims() - with the help of this method we can get the expanded dimension of the array. can convert a 1D arr to 2D array and so on.

In [18]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [19]:
a.shape

(15,)

In [20]:
np.expand_dims(a, axis=0)

array([[70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64]])

In [21]:
np.expand_dims(a, axis=1).shape

(15, 1)

    np.where() - returns the indices of elements where the the given condition is satisfied 

In [22]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [23]:
np.where(a > 50)

(array([ 0,  3,  8,  9, 13, 14], dtype=int64),)

In [24]:
#replace alll values greater than 50 with 0
#np.where(condition , true = kya krna h, false)
np.where(a > 50 , 0 , a)

array([ 0, 41, 46,  0, 10, 24, 34, 50,  0,  0, 41, 35, 19,  0,  0])

In [25]:
np.where(a % 2 == 0, 45 , a)

array([45, 41, 45, 45, 45, 45, 45, 45, 45, 45, 41, 35, 19, 75, 45])

    np.argmax() - returns the indices of the max element of the array on a particular axis. 

In [26]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [27]:
np.argmax(a)

8

In [28]:
b

array([[35, 24, 55, 72],
       [37, 11, 56, 70],
       [40, 18, 75, 85],
       [79, 92, 18,  2],
       [79, 19, 37, 64],
       [68,  5, 91, 52]])

In [29]:
import numpy as np
np.argmax(b, axis = 0)

array([3, 3, 5, 2], dtype=int64)

    np.argmin()

In [30]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [31]:
np.argmin(a)

4

    np.cumsum() - used when we want to find the cummalative sum of arr elements over a given time.

In [32]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [33]:
np.cumsum(a)

array([ 70, 111, 157, 245, 255, 279, 313, 363, 459, 541, 582, 617, 636,
       711, 775])

In [34]:
np.cumsum(b)

array([  35,   59,  114,  186,  223,  234,  290,  360,  400,  418,  493,
        578,  657,  749,  767,  769,  848,  867,  904,  968, 1036, 1041,
       1132, 1184])

In [35]:
np.cumsum(b, axis=0)

array([[ 35,  24,  55,  72],
       [ 72,  35, 111, 142],
       [112,  53, 186, 227],
       [191, 145, 204, 229],
       [270, 164, 241, 293],
       [338, 169, 332, 345]])

In [36]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [37]:
#cumprod
np.cumprod(a)


array([         70,        2870,      132020,    11617760,   116177600,
       -1506704896,   311641088, -1597814784,  1228603392,  1961230336,
       -1193934848,  1161953280,   602275840, -2073952256,   411041792])

    np.percentile() - used to compute the nth percentile of the given data(array elements) along specified axis

In [38]:
np.percentile(a, 100)

96.0

In [39]:
np.percentile(a, 0)

10.0

In [40]:
np.percentile(a, 50)

46.0

    np.histogram()- which represents the frequency of the data distribution in the graphical form

In [41]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [42]:
#gives number of items in the given interval
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 1, 2, 3, 1, 1, 2, 2, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

    np.corrcoef() - returns pearson product-moment corelation coefficients. corelation is b/w -1 to 1 where 0 represent no relation and 1 represents positive relation.

In [43]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

    np.isin() -  we can see that one arr having values are checked in the different numpy array are having

In [44]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [47]:
items= [70,41]
a[np.isin( a, items)]

array([70, 41, 41])

    np.flip() - reverse the order of array along the specified axis , preserving the shape of the array.
    

In [46]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [48]:
np.flip(a)

array([64, 75, 19, 35, 41, 82, 96, 50, 34, 24, 10, 88, 46, 41, 70])

In [50]:
b

array([[35, 24, 55, 72],
       [37, 11, 56, 70],
       [40, 18, 75, 85],
       [79, 92, 18,  2],
       [79, 19, 37, 64],
       [68,  5, 91, 52]])

In [49]:
np.flip(b)

array([[52, 91,  5, 68],
       [64, 37, 19, 79],
       [ 2, 18, 92, 79],
       [85, 75, 18, 40],
       [70, 56, 11, 37],
       [72, 55, 24, 35]])

In [51]:
np.flip(b , axis = 0)

array([[68,  5, 91, 52],
       [79, 19, 37, 64],
       [79, 92, 18,  2],
       [40, 18, 75, 85],
       [37, 11, 56, 70],
       [35, 24, 55, 72]])

    np.put() - replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [52]:
a

array([70, 41, 46, 88, 10, 24, 34, 50, 96, 82, 41, 35, 19, 75, 64])

In [53]:
np.put(a , [0,1] , [700,410])

In [54]:
a

array([700, 410,  46,  88,  10,  24,  34,  50,  96,  82,  41,  35,  19,
        75,  64])

    np.delete() - returns a new array with the deletion of subarrays along with the mentioned axis.

In [56]:
#pass the index or the list
np.delete(a,0)

array([410,  46,  88,  10,  24,  34,  50,  96,  82,  41,  35,  19,  75,
        64])

    set functions:
    -np.union1d
    -np.intersect1d
    -np.setdiff1d - set difference
    -np.setxor1d - set xor- removes commonn and keep others
    -np.in1d

In [58]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [59]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
np.intersect1d(m,n)

array([3, 4, 5])

In [61]:
np.setdiff1d(m,n)

array([1, 2])

In [62]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [64]:
np.in1d(m,1)

array([ True, False, False, False, False])

    np.clip()- is used to clip(limit) the values in an array

In [65]:
a

array([700, 410,  46,  88,  10,  24,  34,  50,  96,  82,  41,  35,  19,
        75,  64])

In [66]:
np.clip(a, a_min = 25, a_max=70)

array([70, 70, 46, 70, 25, 25, 34, 50, 70, 70, 41, 35, 25, 70, 64])